config/routes.rb
RsvpApp::Application.routes.draw do

  resources :users do 
    resources :events
  end

  resources :events do
    resources :invites
  end

  resource :invites

  

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :invites
end

app/models/invite.rb
class Invite < ActiveRecord::Base
	belongs_to :event


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
  end

  # GET /events/new
  def new
    @event = Event.new(:user_id => params[:user_id])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :user_id)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

 before_action :set_event, only: [:show, :edit, :update, :destroy]


	def new
		@invites = Invite.where(:event_id => params[:event_id])
		@invite = Invite.new(:event_id => params[:event_id])
	end

	def create
    @invite = Invite.new(:name => params[:invite][:name],:event_id => params[:invite][:event_id])
    @invite.save
    redirect_to new_event_invite_path(@invite.event_id)
  end

	def show
		@invite = Invite.find(params[:id])
	end

	def edit
		@invite = Invite.find(params[:id])
  end

 	def update
 		@invite = Invite.find(params[:id])
 		@invite.rsvp = true
 		@invite.save
 		redirect_to event_path(@invite.event)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper

	def attendee_list(invite)
		if invite.rsvp 
			"I'm Attending!"
		else
			link_to 'RSVP', edit_invites_path(invite)
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/events/new.html.erb
<h1>New Event!!!!!!!!!!!</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Event Creator:</strong>
  <%= @event.user.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <%= link_to 'Invite Your Friends', new_event_invite_path(@event) %>
</p>

<% render 'invites/invite_list.html.erb',:invites => @event.invites %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/invites/_invite_list.html.erb
<h3>Invitees</h3>

<ul>
<% invites.each do |invite| %>

	<li><%= invite.name %>|
		<%= attendee_list(invite) %>
		<% end %>
</ul>

app/views/invites/edit.html.erb
<h1>RSVP</h1>


<%= form_for(@invite) do |f| %>

 	<div class="actions"> s
    <%= f.submit "I am attending!"%>

  </div>

<% end %>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/invites/new.html.erb
<h1><%= link_to @invite.event.name, event_path(@invite.event) %></h1>
<hr>
<br>

<%= form_for(@invite) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.hidden_field :event_id %><br>
  </div>

	<div class="actions">
    <%= f.submit %>
  </div>
 <% end %>

<hr> 

<h3> Invitees </h3>
 <ul>
 	<% @invites.each do |invite| %>
 		<li><%= invite.name %></li>
 	<% end %>
 </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RsvpApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th><br>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(@user) %></td>
        <td><%= link_to 'Edit', edit_user_path(@user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
	<strong>Events Created:</strong>
	<ul>
	<% @user.events.each do |event|%>
		<li><%= link_to event.name, user_event_path(@user, event)%></li>
	<% end %>		
	</ul>

</p>

<p>
	<%= link_to 'Create New Event', new_user_event_path(@user) %>
</p>
<%= link_to 'Back', users_path %>